#Nama : Annisa Nurlaili Aulia Safitri
#Tugas
# 1. Tentukan determinan matriks berikut:

$$\displaystyle A = \left( \begin{array}{cc}
1 & 2 \\
3 & 4
\end{array}
\right)
$$

#2. Tentukan invers Matriks Berikut:

$$\displaystyle B = \left( \begin{array}{cc}
10 & -22 \\
3 & 45
\end{array}
\right)
$$

#3. Tentukan apakah matriks berikut berkondisi buruk:
$$\displaystyle C = \left( \begin{array}{cc}
1 & 10^{-10} \\
10^{-10} & 1
\end{array}
\right)
$$

#4. Tentukan apakah sistem persamaan linier berikut memiliki solusi. Jika ada, bagaimana solusinya?

$$\displaystyle A = \left( \begin{array}{cc}
1 & 2 \\
3 & 4
\end{array}
\right) $$


$$\displaystyle
b =  \left( \begin{array}{cc}
5 & 6
\end{array}
\right) \\
$$

#5. Tentukan dimensi ruang nol matriks berikut:


$$\displaystyle
C =
\left(
\begin{array}{ccc}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{array}
\right)
$$

#Jawaban

#1. Menentukan determinan matriks

In [1]:
import numpy as np

# Membuat matriks 2x2
A = np.array([[1, 2], [3, 4]])

# Menghitung determinan matriks
determinant = np.linalg.det(A)

print(determinant)

-2.0000000000000004


#2. Menentukan invers matriks

In [2]:
import numpy as np

# Membuat matriks 2x2
B = np.array([[10, -22], [3, 45]])

# Menghitung invers matriks
inverse_of_B = np.linalg.inv(B)

print(inverse_of_B)

[[ 0.0872093   0.04263566]
 [-0.00581395  0.01937984]]


#3. Menentukan keadaan matriks

In [13]:
from numpy.linalg import cond
import numpy as np

C = np.array([[1, 10**-10],
              [10**-10, 1]])

print('Condition number:\n', cond(C))

Condition number:
 1.0000000002


#4. Menentukan sistem persamaan linier

In [14]:
from numpy.linalg import matrix_rank
import numpy as np

A = np.array([[1,2],
              [3,4]])

print('Rank:\n', matrix_rank(A))
B = np.array([[5],[6]])
A_B = np.concatenate((A, B), axis = 1)
print('Augmented matrix:\n', A_B)

Rank:
 2
Augmented matrix:
 [[1 2 5]
 [3 4 6]]


#5. Menentukan dimensi ruang nol

In [24]:
import numpy as np

C = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

null_space, _, _, _ = np.linalg.lstsq(C, np.zeros(C.shape[0]))
null_space_dimension = len(C[0]) - np.linalg.matrix_rank(C)

print("Matriks C:")
print(C)
print("\nSolusi homogen (kernel):")
print(null_space)
print("\nDimensi ruang nol:")
print(null_space_dimension)

Matriks C:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Solusi homogen (kernel):
[0. 0. 0.]

Dimensi ruang nol:
1


<ipython-input-24-38cf16fb623b>:7: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  null_space, _, _, _ = np.linalg.lstsq(C, np.zeros(C.shape[0]))
